### PR TITLE
I want to win

### PR DESCRIPTION
**Pull request by jakethekoenig**
Please accept

### CODE REVIEW

**Comment by kevmo314** [comment]
Haha I appreciate the laugh. Sent it back to you, don't play again :P

**Comment by kevmo314** [comment]
I lied, Coinbase won't let me send ETH right now. I'll send it when I can.

**Comment by jakethekoenig** [comment]
You don't have to send it back. The rules are the rules. Thanks for offering though.

**Comment by kevmo314** [comment]
I sent half back. At least for the entertainment :)

**Pull request closed without merging**
